version: '3.4'

services:
  workshop:
    image: lucpod/workshop
    command: tail -f /var/log/dmesg
    volumes:
      - ".:/home/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - 3000:3000
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_OUTPUT_FORMAT: ${AWS_OUTPUT_FORMAT}
      PARENT_PWD: ${PWD}
