version: '3.4'

services:
  workshop:
    image: lucpod/workshop
    volumes:
      - ".:/home/workspace"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_OUTPUT_FORMAT: ${AWS_OUTPUT_FORMAT}
    restart: always
